version: 2
jobs:
  setEnv1:
    steps:
      - checkout
      - run:
          name: Make dirs
          command: |
            mkdir app
            mkdir admin
      - run:
          name: Go to folder 1
          command: |
            cd app
            echo "Hello from app"
      - run:
          name: Go to folder 2
          command: |
            cd admin
            echo "Hello from admin"


# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - setEnv1:
#           context: org-global
#       - setEnv2:
#           context: admin
#       - build:
#           context: app
#           requires:
#             - setEnv1
#       - build:
#           context: admin
#           requires:
#             - setEnv2
