version: 2
jobs:
  setEnv1:
    steps:
      - checkout
      - run:
          name: Set variable to app
          command: echo 'export TEST_ENV="app"' >> $BASH_ENV

  setEnv2:
    steps:
      - checkout
      - run:
          name: Set variable to app
          command: echo 'export TEST_ENV="admin"' >> $BASH_ENV

  build:
    steps:
      - checkout
      - run:
          name: Build
          command: echo ${TEST_ENV}


workflows:
  version: 2
  build_and_test:
    jobs:
      - setEnv1:
          context: app
      - setEnv2:
          context: admin
      - build:
          context: app
          requires:
            - setEnv1
      - build:
          context: admin
          requires:
            - setEnv2
